/* Auto-generated by scripts/sync-jekyll-content.mjs. Do not edit by hand. */
import type { LoadedPosts } from "./posts";

export const jekyllSnapshot: LoadedPosts = {
  "posts": [
    {
      "day": 172,
      "title": "Parallel Agents Without Collisions: Task Graphs and Git Worktrees",
      "date": "2026-07-22",
      "url": "https://juribuora.github.io/blog/2026/07/22/day-172.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "git",
        "worktrees",
        "multiagent",
        "isolation",
        "learningprocess"
      ],
      "slug": "day-172",
      "sourcePath": "Blog/_posts/2026-07-22-day-172.md",
      "contentPath": "/generated/posts/blog/172.json"
    },
    {
      "day": 171,
      "title": "Five Ways My Automation Faked Success (and the Fail-Closed Fixes)",
      "date": "2026-07-21",
      "url": "https://juribuora.github.io/blog/2026/07/21/day-171.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "failclosed",
        "verification",
        "supervisor",
        "reliability",
        "learningprocess"
      ],
      "slug": "day-171",
      "sourcePath": "Blog/_posts/2026-07-21-day-171.md",
      "contentPath": "/generated/posts/blog/171.json"
    },
    {
      "day": 170,
      "title": "Making Security Work Clear Without Overselling It",
      "date": "2026-07-20",
      "url": "https://juribuora.github.io/blog/2026/07/20/day-170.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "documentation",
        "verification",
        "technicalwriting",
        "learningprocess"
      ],
      "slug": "day-170",
      "sourcePath": "Blog/_posts/2026-07-20-day-170.md",
      "contentPath": "/generated/posts/blog/170.json"
    },
    {
      "day": 169,
      "title": "Why Safe Rollouts Use Feature Flags, Fixtures, and Evidence Gates",
      "date": "2026-07-19",
      "url": "https://juribuora.github.io/blog/2026/07/19/day-169.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "changemanagement",
        "featureflags",
        "testing",
        "riskmanagement",
        "learningprocess"
      ],
      "slug": "day-169",
      "sourcePath": "Blog/_posts/2026-07-19-day-169.md",
      "contentPath": "/generated/posts/blog/169.json"
    },
    {
      "day": 168,
      "title": "Secure Artifact Delivery: Narrow Links, Verified Bytes, and No Duplicate Sends",
      "date": "2026-07-18",
      "url": "https://juribuora.github.io/blog/2026/07/18/day-168.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "integrity",
        "authorization",
        "hashing",
        "securedelivery",
        "learningprocess"
      ],
      "slug": "day-168",
      "sourcePath": "Blog/_posts/2026-07-18-day-168.md",
      "contentPath": "/generated/posts/blog/168.json"
    },
    {
      "day": 167,
      "title": "Approval-Gated Automation: Making Privileged Agent Work Accountable",
      "date": "2026-07-17",
      "url": "https://juribuora.github.io/blog/2026/07/17/day-167.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "automationsecurity",
        "leastprivilege",
        "approvals",
        "auditability",
        "learningprocess"
      ],
      "slug": "day-167",
      "sourcePath": "Blog/_posts/2026-07-17-day-167.md",
      "contentPath": "/generated/posts/blog/167.json"
    },
    {
      "day": 166,
      "title": "Resilient Sessions: What a Torn Journal Taught Me About Safe AI State",
      "date": "2026-07-16",
      "url": "https://juribuora.github.io/blog/2026/07/16/day-166.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "resilience",
        "dataintegrity",
        "recovery",
        "logging",
        "learningprocess"
      ],
      "slug": "day-166",
      "sourcePath": "Blog/_posts/2026-07-16-day-166.md",
      "contentPath": "/generated/posts/blog/166.json"
    },
    {
      "day": 165,
      "title": "Bounded Context, Better Decisions: Testing AI Agent Memory Without Blind Trust",
      "date": "2026-07-15",
      "url": "https://juribuora.github.io/blog/2026/07/15/day-165.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "aisecurity",
        "provenance",
        "dataintegrity",
        "benchmarking",
        "learningprocess"
      ],
      "slug": "day-165",
      "sourcePath": "Blog/_posts/2026-07-15-day-165.md",
      "contentPath": "/generated/posts/blog/165.json"
    },
    {
      "day": 164,
      "title": "Verifying the Verifier: A False-Positive Streak in My Own Checks",
      "date": "2026-07-14",
      "url": "https://juribuora.github.io/blog/2026/07/14/day-164.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "verification",
        "falsepositives",
        "detectionengineering",
        "reliability",
        "learningprocess"
      ],
      "slug": "day-164",
      "sourcePath": "Blog/_posts/2026-07-14-day-164.md",
      "contentPath": "/generated/posts/blog/164.json"
    },
    {
      "day": 163,
      "title": "Model Fleet Ops: Migrating the Coding Lane to Gemma and Budgeting Tokens Like a Resource",
      "date": "2026-07-13",
      "url": "https://juribuora.github.io/blog/2026/07/13/day-163.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "localllm",
        "lifecycle",
        "resourcemanagement",
        "benchmarking",
        "learningprocess"
      ],
      "slug": "day-163",
      "sourcePath": "Blog/_posts/2026-07-13-day-163.md",
      "contentPath": "/generated/posts/blog/163.json"
    },
    {
      "day": 162,
      "title": "An AI Secretary With a Kill Switch: Calendars, Sender Policy, and Emergency Control",
      "date": "2026-07-12",
      "url": "https://juribuora.github.io/blog/2026/07/12/day-162.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "automation",
        "privacy",
        "emailsecurity",
        "failsafe",
        "learningprocess"
      ],
      "slug": "day-162",
      "sourcePath": "Blog/_posts/2026-07-12-day-162.md",
      "contentPath": "/generated/posts/blog/162.json"
    },
    {
      "day": 161,
      "title": "Hardening the iOS Companion: Untrusted Links, Redacted Errors, and the 'Full Power' Question",
      "date": "2026-07-11",
      "url": "https://juribuora.github.io/blog/2026/07/11/day-161.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "ios",
        "appsec",
        "mobilesecurity",
        "testing",
        "learningprocess"
      ],
      "slug": "day-161",
      "sourcePath": "Blog/_posts/2026-07-11-day-161.md",
      "contentPath": "/generated/posts/blog/161.json"
    },
    {
      "day": 160,
      "title": "Tailscale Broke My Stack: Node Identity, Hostnames, and Private Services",
      "date": "2026-07-10",
      "url": "https://juribuora.github.io/blog/2026/07/10/day-160.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "tailscale",
        "networking",
        "dns",
        "availability",
        "learningprocess"
      ],
      "slug": "day-160",
      "sourcePath": "Blog/_posts/2026-07-10-day-160.md",
      "contentPath": "/generated/posts/blog/160.json"
    },
    {
      "day": 159,
      "title": "Widening an Agent's Write Scope on Purpose (and Making Its Findings Earn Evidence)",
      "date": "2026-07-09",
      "url": "https://juribuora.github.io/blog/2026/07/09/day-159.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "leastprivilege",
        "localai",
        "accesscontrol",
        "verification",
        "learningprocess"
      ],
      "slug": "day-159",
      "sourcePath": "Blog/_posts/2026-07-09-day-159.md",
      "contentPath": "/generated/posts/blog/159.json"
    },
    {
      "day": 158,
      "title": "Gated Autonomy: A Phone Approval Loop Before Any Agent Sends Anything",
      "date": "2026-07-08",
      "url": "https://juribuora.github.io/blog/2026/07/08/day-158.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "humanintheloop",
        "approvals",
        "automation",
        "emailsecurity",
        "learningprocess"
      ],
      "slug": "day-158",
      "sourcePath": "Blog/_posts/2026-07-08-day-158.md",
      "contentPath": "/generated/posts/blog/158.json"
    },
    {
      "day": 157,
      "title": "WebCheckup: Turning the Mini-Audit Into a Real Multilingual Service",
      "date": "2026-07-07",
      "url": "https://juribuora.github.io/blog/2026/07/07/day-157.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webcheckup",
        "auditing",
        "reporting",
        "localization",
        "learningprocess"
      ],
      "slug": "day-157",
      "sourcePath": "Blog/_posts/2026-07-07-day-157.md",
      "contentPath": "/generated/posts/blog/157.json"
    },
    {
      "day": 156,
      "title": "Too Many Projects: Auditing My Own Tool Sprawl Like an Asset Inventory",
      "date": "2026-07-06",
      "url": "https://juribuora.github.io/blog/2026/07/06/day-156.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "assetinventory",
        "governance",
        "documentation",
        "decommissioning",
        "learningprocess"
      ],
      "slug": "day-156",
      "sourcePath": "Blog/_posts/2026-07-06-day-156.md",
      "contentPath": "/generated/posts/blog/156.json"
    },
    {
      "day": 155,
      "title": "Linux User and Group Management as Access Control Practice",
      "date": "2026-07-05",
      "url": "https://juribuora.github.io/blog/2026/07/05/day-155.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "accesscontrol",
        "authentication",
        "authorization",
        "googlecybersecuritycertificate",
        "learningprocess"
      ],
      "slug": "day-155",
      "sourcePath": "Blog/_posts/2026-07-05-day-155.md",
      "contentPath": "/generated/posts/blog/155.json"
    },
    {
      "day": 154,
      "title": "Building a Cybersecurity Glossary Without Breaking My Notes",
      "date": "2026-07-04",
      "url": "https://juribuora.github.io/blog/2026/07/04/day-154.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "obsidian",
        "knowledgemanagement",
        "glossary",
        "validation",
        "learningprocess"
      ],
      "slug": "day-154",
      "sourcePath": "Blog/_posts/2026-07-04-day-154.md",
      "contentPath": "/generated/posts/blog/154.json"
    },
    {
      "day": 153,
      "title": "Testing Hermes Agent: Strong First Builds, Weak Self-Verification",
      "date": "2026-07-03",
      "url": "https://juribuora.github.io/blog/2026/07/03/day-153.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "autonomousagents",
        "verification",
        "hermes",
        "webtesting",
        "learningprocess"
      ],
      "slug": "day-153",
      "sourcePath": "Blog/_posts/2026-07-03-day-153.md",
      "contentPath": "/generated/posts/blog/153.json"
    },
    {
      "day": 152,
      "title": "Building an AI Inference Orchestrator With Routing, Retries, and Cost Awareness",
      "date": "2026-07-02",
      "url": "https://juribuora.github.io/blog/2026/07/02/day-152.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "aios",
        "orchestration",
        "reliability",
        "costtracking",
        "learningprocess"
      ],
      "slug": "day-152",
      "sourcePath": "Blog/_posts/2026-07-02-day-152.md",
      "contentPath": "/generated/posts/blog/152.json"
    },
    {
      "day": 151,
      "title": "Benchmarking My Local LLM Stack Instead of Trusting Vibes",
      "date": "2026-07-01",
      "url": "https://juribuora.github.io/blog/2026/07/01/day-151.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "localllm",
        "benchmarking",
        "ollama",
        "ds4",
        "lmstudio",
        "learningprocess"
      ],
      "slug": "day-151",
      "sourcePath": "Blog/_posts/2026-07-01-day-151.md",
      "contentPath": "/generated/posts/blog/151.json"
    },
    {
      "day": 150,
      "title": "Remote Agent Hub and the Discipline of Honest Feature Labels",
      "date": "2026-06-30",
      "url": "https://juribuora.github.io/blog/2026/06/30/day-150.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "remoteagenthub",
        "productsecurity",
        "accesscontrol",
        "localfirst",
        "learningprocess"
      ],
      "slug": "day-150",
      "sourcePath": "Blog/_posts/2026-06-30-day-150.md",
      "contentPath": "/generated/posts/blog/150.json"
    },
    {
      "day": 149,
      "title": "Turning My iPhone Into a Command Center for Local Agents",
      "date": "2026-06-29",
      "url": "https://juribuora.github.io/blog/2026/06/29/day-149.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "ios",
        "localagents",
        "operationalsecurity",
        "ux",
        "learningprocess"
      ],
      "slug": "day-149",
      "sourcePath": "Blog/_posts/2026-06-29-day-149.md",
      "contentPath": "/generated/posts/blog/149.json"
    },
    {
      "day": 148,
      "title": "Building Least-Privilege Tool Profiles for My AI Agents (and Finding My Own Risk Scorer Was Inverted)",
      "date": "2026-06-28",
      "url": "https://juribuora.github.io/blog/2026/06/28/day-148.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "leastprivilege",
        "mcp",
        "permissionmodel",
        "riskscoring",
        "learningprocess"
      ],
      "slug": "day-148",
      "sourcePath": "Blog/_posts/2026-06-28-day-148.md",
      "contentPath": "/generated/posts/blog/148.json"
    },
    {
      "day": 147,
      "title": "'Build Succeeded' Isn't Proof: Writing a Real UI Test for the Auth Flow",
      "date": "2026-06-27",
      "url": "https://juribuora.github.io/blog/2026/06/27/day-147.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "testing",
        "authentication",
        "ios",
        "qualityassurance",
        "learningprocess"
      ],
      "slug": "day-147",
      "sourcePath": "Blog/_posts/2026-06-27-day-147.md",
      "contentPath": "/generated/posts/blog/147.json"
    },
    {
      "day": 146,
      "title": "Giving My Local Agent Daemon Real Auth (And Almost Leaking the Token in the 401 Page)",
      "date": "2026-06-26",
      "url": "https://juribuora.github.io/blog/2026/06/26/day-146.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "accesscontrol",
        "authentication",
        "ios",
        "localai",
        "learningprocess"
      ],
      "slug": "day-146",
      "sourcePath": "Blog/_posts/2026-06-26-day-146.md",
      "contentPath": "/generated/posts/blog/146.json"
    },
    {
      "day": 145,
      "title": "Productizing a Website Security Mini-Audit, and Finding an Access Gap in My Own Funnel",
      "date": "2026-06-25",
      "url": "https://juribuora.github.io/blog/2026/06/25/day-145.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "websecurity",
        "auditing",
        "business",
        "accesscontrol",
        "learningprocess"
      ],
      "slug": "day-145",
      "sourcePath": "Blog/_posts/2026-06-25-day-145.md",
      "contentPath": "/generated/posts/blog/145.json"
    },
    {
      "day": 144,
      "title": "A 348-Term Glossary and the False Positives That Came With It",
      "date": "2026-06-24",
      "url": "https://juribuora.github.io/blog/2026/06/24/day-144.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "knowledgemanagement",
        "obsidian",
        "websecurity",
        "linux",
        "learningprocess"
      ],
      "slug": "day-144",
      "sourcePath": "Blog/_posts/2026-06-24-day-144.md",
      "contentPath": "/generated/posts/blog/144.json"
    },
    {
      "day": 143,
      "title": "Building a Local MITRE ATT&CK Technique Library from My Own Notes",
      "date": "2026-06-23",
      "url": "https://juribuora.github.io/blog/2026/06/23/day-143.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "mitre",
        "knowledgemanagement",
        "obsidian",
        "detectionengineering",
        "learningprocess"
      ],
      "slug": "day-143",
      "sourcePath": "Blog/_posts/2026-06-23-day-143.md",
      "contentPath": "/generated/posts/blog/143.json"
    },
    {
      "day": 142,
      "title": "Benchmarking an Autonomous Agent: Strong One-Shot Builds, Unreliable Self-Debugging",
      "date": "2026-06-22",
      "url": "https://juribuora.github.io/blog/2026/06/22/day-142.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "localai",
        "benchmarking",
        "autonomy",
        "verification",
        "learningprocess"
      ],
      "slug": "day-142",
      "sourcePath": "Blog/_posts/2026-06-22-day-142.md",
      "contentPath": "/generated/posts/blog/142.json"
    },
    {
      "day": 141,
      "title": "A Human Memory Layer: The RAG Vault My Agents Write and I Read Anywhere",
      "date": "2026-06-21",
      "url": "https://juribuora.github.io/blog/2026/06/21/day-141.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "knowledgemanagement",
        "obsidian",
        "localai",
        "datagovernance",
        "learningprocess"
      ],
      "slug": "day-141",
      "sourcePath": "Blog/_posts/2026-06-21-day-141.md",
      "contentPath": "/generated/posts/blog/141.json"
    },
    {
      "day": 140,
      "title": "AI-OS: Governance, Routing, and a Verification Gateway for My Local Agents",
      "date": "2026-06-20",
      "url": "https://juribuora.github.io/blog/2026/06/20/day-140.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "localai",
        "governance",
        "orchestration",
        "verification",
        "learningprocess"
      ],
      "slug": "day-140",
      "sourcePath": "Blog/_posts/2026-06-20-day-140.md",
      "contentPath": "/generated/posts/blog/140.json"
    },
    {
      "day": 139,
      "title": "Benchmarking a Local LLM Coding Stack: Harness, Routing, and Review Findings",
      "date": "2026-06-19",
      "url": "https://juribuora.github.io/blog/2026/06/19/day-139.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "localai",
        "benchmarking",
        "codereview",
        "reliability",
        "learningprocess"
      ],
      "slug": "day-139",
      "sourcePath": "Blog/_posts/2026-06-19-day-139.md",
      "contentPath": "/generated/posts/blog/139.json"
    },
    {
      "day": 138,
      "title": "An iOS Companion for My Local Agent, Private by Design",
      "date": "2026-06-18",
      "url": "https://juribuora.github.io/blog/2026/06/18/day-138.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "ios",
        "tailscale",
        "remoteaccess",
        "swiftui",
        "learningprocess"
      ],
      "slug": "day-138",
      "sourcePath": "Blog/_posts/2026-06-18-day-138.md",
      "contentPath": "/generated/posts/blog/138.json"
    },
    {
      "day": 137,
      "title": "Running DS4: A Serious Local Model on a Laptop With Limits",
      "date": "2026-06-17",
      "url": "https://juribuora.github.io/blog/2026/06/17/day-137.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "localai",
        "ds4",
        "resourcemanagement",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-137",
      "sourcePath": "Blog/_posts/2026-06-17-day-137.md",
      "contentPath": "/generated/posts/blog/137.json"
    },
    {
      "day": 136,
      "title": "Linux Permissions and Authorization: A Google Cybersecurity Certificate Portfolio Activity",
      "date": "2026-06-16",
      "url": "https://juribuora.github.io/blog/2026/06/16/day-136.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "accesscontrol",
        "googlecert",
        "portfolio",
        "learningprocess"
      ],
      "slug": "day-136",
      "sourcePath": "Blog/_posts/2026-06-16-day-136.md",
      "contentPath": "/generated/posts/blog/136.json"
    },
    {
      "day": 135,
      "title": "Auditing My Own Website, Then Fixing What the Report Found",
      "date": "2026-06-15",
      "url": "https://juribuora.github.io/blog/2026/06/15/day-135.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "websecurity",
        "hardening",
        "githubpages",
        "remediation",
        "learningprocess"
      ],
      "slug": "day-135",
      "sourcePath": "Blog/_posts/2026-06-15-day-135.md",
      "contentPath": "/generated/posts/blog/135.json"
    },
    {
      "day": 134,
      "title": "Building a Website Trust & Security Mini-Audit Service",
      "date": "2026-06-14",
      "url": "https://juribuora.github.io/blog/2026/06/14/day-134.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "websecurity",
        "auditing",
        "reporting",
        "business",
        "learningprocess"
      ],
      "slug": "day-134",
      "sourcePath": "Blog/_posts/2026-06-14-day-134.md",
      "contentPath": "/generated/posts/blog/134.json"
    },
    {
      "day": 133,
      "title": "When the Learning Log Breaks: Fixing My Blog's Own Publishing Pipeline",
      "date": "2026-06-13",
      "url": "https://juribuora.github.io/blog/2026/06/13/day-133.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "githubpages",
        "cicd",
        "jekyll",
        "troubleshooting",
        "learningprocess"
      ],
      "slug": "day-133",
      "sourcePath": "Blog/_posts/2026-06-13-day-133.md",
      "contentPath": "/generated/posts/blog/133.json"
    },
    {
      "day": 132,
      "title": "Giving a Local LLM Hands: LM Studio, Function Calling, and MCP Servers",
      "date": "2026-06-12",
      "url": "https://juribuora.github.io/blog/2026/06/12/day-132.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "localai",
        "mcp",
        "tooling",
        "automation",
        "learningprocess"
      ],
      "slug": "day-132",
      "sourcePath": "Blog/_posts/2026-06-12-day-132.md",
      "contentPath": "/generated/posts/blog/132.json"
    },
    {
      "day": 131,
      "title": "Project Retrospective: Turning a Real Website Build Into Portfolio Evidence",
      "date": "2026-06-11",
      "url": "https://juribuora.github.io/blog/2026/06/11/day-131.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-131",
      "sourcePath": "Blog/_posts/2026-06-11-day-131.md",
      "contentPath": "/generated/posts/blog/131.json"
    },
    {
      "day": 130,
      "title": "Public Website Security Review for a Static Business Site",
      "date": "2026-06-10",
      "url": "https://juribuora.github.io/blog/2026/06/10/day-130.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-130",
      "sourcePath": "Blog/_posts/2026-06-10-day-130.md",
      "contentPath": "/generated/posts/blog/130.json"
    },
    {
      "day": 129,
      "title": "Testing, Linting, Type Checking, and Build Validation",
      "date": "2026-06-09",
      "url": "https://juribuora.github.io/blog/2026/06/09/day-129.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-129",
      "sourcePath": "Blog/_posts/2026-06-09-day-129.md",
      "contentPath": "/generated/posts/blog/129.json"
    },
    {
      "day": 128,
      "title": "Privacy, Analytics, and Consent-Aware Configuration",
      "date": "2026-06-08",
      "url": "https://juribuora.github.io/blog/2026/06/08/day-128.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-128",
      "sourcePath": "Blog/_posts/2026-06-08-day-128.md",
      "contentPath": "/generated/posts/blog/128.json"
    },
    {
      "day": 127,
      "title": "Custom Domain, DNS, and Website Availability",
      "date": "2026-06-07",
      "url": "https://juribuora.github.io/blog/2026/06/07/day-127.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-127",
      "sourcePath": "Blog/_posts/2026-06-07-day-127.md",
      "contentPath": "/generated/posts/blog/127.json"
    },
    {
      "day": 126,
      "title": "GitHub Pages Deployment and CI/CD Trust Boundaries",
      "date": "2026-06-06",
      "url": "https://juribuora.github.io/blog/2026/06/06/day-126.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-126",
      "sourcePath": "Blog/_posts/2026-06-06-day-126.md",
      "contentPath": "/generated/posts/blog/126.json"
    },
    {
      "day": 125,
      "title": "Image Optimization and Performance as Operational Security",
      "date": "2026-06-05",
      "url": "https://juribuora.github.io/blog/2026/06/05/day-125.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-125",
      "sourcePath": "Blog/_posts/2026-06-05-day-125.md",
      "contentPath": "/generated/posts/blog/125.json"
    },
    {
      "day": 124,
      "title": "SEO, Metadata, and Structured Data Without Forgetting Security",
      "date": "2026-06-04",
      "url": "https://juribuora.github.io/blog/2026/06/04/day-124.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-124",
      "sourcePath": "Blog/_posts/2026-06-04-day-124.md",
      "contentPath": "/generated/posts/blog/124.json"
    },
    {
      "day": 123,
      "title": "Contact Forms, Validation, and Anti-Spam Thinking",
      "date": "2026-06-03",
      "url": "https://juribuora.github.io/blog/2026/06/03/day-123.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-123",
      "sourcePath": "Blog/_posts/2026-06-03-day-123.md",
      "contentPath": "/generated/posts/blog/123.json"
    },
    {
      "day": 122,
      "title": "Mobile-First UX and Customer-Facing Reliability",
      "date": "2026-06-02",
      "url": "https://juribuora.github.io/blog/2026/06/02/day-122.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-122",
      "sourcePath": "Blog/_posts/2026-06-02-day-122.md",
      "contentPath": "/generated/posts/blog/122.json"
    },
    {
      "day": 121,
      "title": "Routing, Pages, and Public Attack Surface",
      "date": "2026-06-01",
      "url": "https://juribuora.github.io/blog/2026/06/01/day-121.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-121",
      "sourcePath": "Blog/_posts/2026-06-01-day-121.md",
      "contentPath": "/generated/posts/blog/121.json"
    },
    {
      "day": 120,
      "title": "Repository Structure and Operational Hygiene",
      "date": "2026-05-31",
      "url": "https://juribuora.github.io/blog/2026/05/31/day-120.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-120",
      "sourcePath": "Blog/_posts/2026-05-31-day-120.md",
      "contentPath": "/generated/posts/blog/120.json"
    },
    {
      "day": 119,
      "title": "React, TypeScript, Vite, and Tailwind as a Production Stack",
      "date": "2026-05-30",
      "url": "https://juribuora.github.io/blog/2026/05/30/day-119.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-119",
      "sourcePath": "Blog/_posts/2026-05-30-day-119.md",
      "contentPath": "/generated/posts/blog/119.json"
    },
    {
      "day": 118,
      "title": "Real Client Website Scope and Business Requirements",
      "date": "2026-05-29",
      "url": "https://juribuora.github.io/blog/2026/05/29/day-118.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "githubpages",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-118",
      "sourcePath": "Blog/_posts/2026-05-29-day-118.md",
      "contentPath": "/generated/posts/blog/118.json"
    },
    {
      "day": 117,
      "title": "macOS Persistence, LaunchDaemons, and Endpoint Triage",
      "date": "2026-05-28",
      "url": "https://juribuora.github.io/blog/2026/05/28/day-117.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "processes",
        "logs",
        "linuxfundamentals",
        "documentation"
      ],
      "slug": "day-117",
      "sourcePath": "Blog/_posts/2026-05-28-day-117.md",
      "contentPath": "/generated/posts/blog/117.json"
    },
    {
      "day": 116,
      "title": "Frontend Architecture, Website Optimization, and GitHub Workflows",
      "date": "2026-05-27",
      "url": "https://juribuora.github.io/blog/2026/05/27/day-116.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "documentation",
        "githubpages",
        "tooling"
      ],
      "slug": "day-116",
      "sourcePath": "Blog/_posts/2026-05-27-day-116.md",
      "contentPath": "/generated/posts/blog/116.json"
    },
    {
      "day": 115,
      "title": "Local AI Models, Coding Agents, and Operational Automation",
      "date": "2026-05-26",
      "url": "https://juribuora.github.io/blog/2026/05/26/day-115.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "documentation",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-115",
      "sourcePath": "Blog/_posts/2026-05-26-day-115.md",
      "contentPath": "/generated/posts/blog/115.json"
    },
    {
      "day": 114,
      "title": "OS, Network, and Cloud Hardening",
      "date": "2026-05-25",
      "url": "https://juribuora.github.io/blog/2026/05/25/day-114.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "linuxfundamentals",
        "learningprocess",
        "documentation"
      ],
      "slug": "day-114",
      "sourcePath": "Blog/_posts/2026-05-25-day-114.md",
      "contentPath": "/generated/posts/blog/114.json"
    },
    {
      "day": 113,
      "title": "Sniffing, Spoofing, and Interception Tactics",
      "date": "2026-05-24",
      "url": "https://juribuora.github.io/blog/2026/05/24/day-113.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "tcpip",
        "learningprocess"
      ],
      "slug": "day-113",
      "sourcePath": "Blog/_posts/2026-05-24-day-113.md",
      "contentPath": "/generated/posts/blog/113.json"
    },
    {
      "day": 112,
      "title": "DoS, DDoS, SYN Floods, Smurf, and Amplification",
      "date": "2026-05-23",
      "url": "https://juribuora.github.io/blog/2026/05/23/day-112.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "tcpip",
        "logs",
        "learningprocess"
      ],
      "slug": "day-112",
      "sourcePath": "Blog/_posts/2026-05-23-day-112.md",
      "contentPath": "/generated/posts/blog/112.json"
    },
    {
      "day": 111,
      "title": "Reading tcpdump-Style Logs and DNS/ICMP Failures",
      "date": "2026-05-22",
      "url": "https://juribuora.github.io/blog/2026/05/22/day-111.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "dns",
        "tcpip",
        "logs",
        "learningprocess"
      ],
      "slug": "day-111",
      "sourcePath": "Blog/_posts/2026-05-22-day-111.md",
      "contentPath": "/generated/posts/blog/111.json"
    },
    {
      "day": 110,
      "title": "Enterprise Network Flow and Attack Surface Mapping",
      "date": "2026-05-21",
      "url": "https://juribuora.github.io/blog/2026/05/21/day-110.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "webfundamentals",
        "learningprocess"
      ],
      "slug": "day-110",
      "sourcePath": "Blog/_posts/2026-05-21-day-110.md",
      "contentPath": "/generated/posts/blog/110.json"
    },
    {
      "day": 109,
      "title": "Firewalls, VPNs, Proxies, Security Zones, and CIDR",
      "date": "2026-05-20",
      "url": "https://juribuora.github.io/blog/2026/05/20/day-109.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "tcpip",
        "learningprocess"
      ],
      "slug": "day-109",
      "sourcePath": "Blog/_posts/2026-05-20-day-109.md",
      "contentPath": "/generated/posts/blog/109.json"
    },
    {
      "day": 108,
      "title": "Network Protocols, Ports, DNS, HTTP, and Remote Access",
      "date": "2026-05-19",
      "url": "https://juribuora.github.io/blog/2026/05/19/day-108.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "dns",
        "http",
        "tcpip",
        "learningprocess"
      ],
      "slug": "day-108",
      "sourcePath": "Blog/_posts/2026-05-19-day-108.md",
      "contentPath": "/generated/posts/blog/108.json"
    },
    {
      "day": 107,
      "title": "Network Architecture, Cloud Networks, and the TCP/IP Model",
      "date": "2026-05-18",
      "url": "https://juribuora.github.io/blog/2026/05/18/day-107.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "tcpip",
        "learningprocess"
      ],
      "slug": "day-107",
      "sourcePath": "Blog/_posts/2026-05-18-day-107.md",
      "contentPath": "/generated/posts/blog/107.json"
    },
    {
      "day": 106,
      "title": "From Risk Management to Portfolio Evidence",
      "date": "2026-05-17",
      "url": "https://juribuora.github.io/blog/2026/05/17/day-106.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "documentation",
        "learningprocess"
      ],
      "slug": "day-106",
      "sourcePath": "Blog/_posts/2026-05-17-day-106.md",
      "contentPath": "/generated/posts/blog/106.json"
    },
    {
      "day": 105,
      "title": "Incident Response Playbooks and Escalation Discipline",
      "date": "2026-05-16",
      "url": "https://juribuora.github.io/blog/2026/05/16/day-105.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "logs",
        "documentation",
        "learningprocess"
      ],
      "slug": "day-105",
      "sourcePath": "Blog/_posts/2026-05-16-day-105.md",
      "contentPath": "/generated/posts/blog/105.json"
    },
    {
      "day": 104,
      "title": "SIEM Logs, Dashboards, and Alert Triage",
      "date": "2026-05-15",
      "url": "https://juribuora.github.io/blog/2026/05/15/day-104.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "logs",
        "learningprocess",
        "documentation"
      ],
      "slug": "day-104",
      "sourcePath": "Blog/_posts/2026-05-15-day-104.md",
      "contentPath": "/generated/posts/blog/104.json"
    },
    {
      "day": 103,
      "title": "Security Frameworks, Controls, NIST CSF, OWASP, and Audits",
      "date": "2026-05-14",
      "url": "https://juribuora.github.io/blog/2026/05/14/day-103.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "documentation",
        "learningprocess"
      ],
      "slug": "day-103",
      "sourcePath": "Blog/_posts/2026-05-14-day-103.md",
      "contentPath": "/generated/posts/blog/103.json"
    },
    {
      "day": 102,
      "title": "Threats, Risks, Vulnerabilities, and the NIST RMF",
      "date": "2026-05-13",
      "url": "https://juribuora.github.io/blog/2026/05/13/day-102.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess",
        "documentation"
      ],
      "slug": "day-102",
      "sourcePath": "Blog/_posts/2026-05-13-day-102.md",
      "contentPath": "/generated/posts/blog/102.json"
    },
    {
      "day": 101,
      "title": "Frameworks, Controls, Ethics, and Analyst Tooling",
      "date": "2026-05-12",
      "url": "https://juribuora.github.io/blog/2026/05/12/day-101.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess",
        "documentation",
        "tooling"
      ],
      "slug": "day-101",
      "sourcePath": "Blog/_posts/2026-05-12-day-101.md",
      "contentPath": "/generated/posts/blog/101.json"
    },
    {
      "day": 100,
      "title": "Attack History, Business Impact, and Security Domains",
      "date": "2026-05-11",
      "url": "https://juribuora.github.io/blog/2026/05/11/day-100.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess",
        "documentation"
      ],
      "slug": "day-100",
      "sourcePath": "Blog/_posts/2026-05-11-day-100.md",
      "contentPath": "/generated/posts/blog/100.json"
    },
    {
      "day": 99,
      "title": "Cybersecurity Analyst Mindset and Phishing Triage",
      "date": "2026-05-10",
      "url": "https://juribuora.github.io/blog/2026/05/10/day-99.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess",
        "documentation"
      ],
      "slug": "day-99",
      "sourcePath": "Blog/_posts/2026-05-10-day-99.md",
      "contentPath": "/generated/posts/blog/99.json"
    },
    {
      "day": 98,
      "title": "Cookie Banners, Technical Cookies, and Website Privacy Checks",
      "date": "2026-05-09",
      "url": "https://juribuora.github.io/blog/2026/05/09/day-98.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "http",
        "logs",
        "documentation",
        "learningprocess"
      ],
      "slug": "day-98",
      "sourcePath": "Blog/_posts/2026-05-09-day-98.md",
      "contentPath": "/generated/posts/blog/98.json"
    },
    {
      "day": 97,
      "title": "Privacy-First Website Analytics",
      "date": "2026-05-08",
      "url": "https://juribuora.github.io/blog/2026/05/08/day-97.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "http",
        "documentation",
        "learningprocess"
      ],
      "slug": "day-97",
      "sourcePath": "Blog/_posts/2026-05-08-day-97.md",
      "contentPath": "/generated/posts/blog/97.json"
    },
    {
      "day": 96,
      "title": "IP Spoofing, Sniffing, and Attack Technique Classification",
      "date": "2026-05-07",
      "url": "https://juribuora.github.io/blog/2026/05/07/day-96.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "tcpip",
        "learningprocess"
      ],
      "slug": "day-96",
      "sourcePath": "Blog/_posts/2026-05-07-day-96.md",
      "contentPath": "/generated/posts/blog/96.json"
    },
    {
      "day": 95,
      "title": "DoS, DDoS, Smurf Attacks, and Amplification",
      "date": "2026-05-06",
      "url": "https://juribuora.github.io/blog/2026/05/06/day-95.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "tcpip",
        "learningprocess"
      ],
      "slug": "day-95",
      "sourcePath": "Blog/_posts/2026-05-06-day-95.md",
      "contentPath": "/generated/posts/blog/95.json"
    },
    {
      "day": 94,
      "title": "DNS and ICMP Traffic Incident Analysis",
      "date": "2026-05-05",
      "url": "https://juribuora.github.io/blog/2026/05/05/day-94.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "dns",
        "tcpip",
        "learningprocess"
      ],
      "slug": "day-94",
      "sourcePath": "Blog/_posts/2026-05-05-day-94.md",
      "contentPath": "/generated/posts/blog/94.json"
    },
    {
      "day": 93,
      "title": "Turning Network Concepts into Incident Reports",
      "date": "2026-05-04",
      "url": "https://juribuora.github.io/blog/2026/05/04/day-93.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "learningprocess"
      ],
      "slug": "day-93",
      "sourcePath": "Blog/_posts/2026-05-04-day-93.md",
      "contentPath": "/generated/posts/blog/93.json"
    },
    {
      "day": 92,
      "title": "Cybersecurity Roles Across the Attack Surface",
      "date": "2026-05-03",
      "url": "https://juribuora.github.io/blog/2026/05/03/day-92.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-92",
      "sourcePath": "Blog/_posts/2026-05-03-day-92.md",
      "contentPath": "/generated/posts/blog/92.json"
    },
    {
      "day": 91,
      "title": "Enterprise Attack Surface and Exploitation Points",
      "date": "2026-05-02",
      "url": "https://juribuora.github.io/blog/2026/05/02/day-91.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "webfundamentals",
        "learningprocess"
      ],
      "slug": "day-91",
      "sourcePath": "Blog/_posts/2026-05-02-day-91.md",
      "contentPath": "/generated/posts/blog/91.json"
    },
    {
      "day": 90,
      "title": "Mapping an Enterprise Network End to End",
      "date": "2026-05-01",
      "url": "https://juribuora.github.io/blog/2026/05/01/day-90.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "webfundamentals",
        "learningprocess"
      ],
      "slug": "day-90",
      "sourcePath": "Blog/_posts/2026-05-01-day-90.md",
      "contentPath": "/generated/posts/blog/90.json"
    },
    {
      "day": 89,
      "title": "From Protocol Memorization to SOC Thinking",
      "date": "2026-04-30",
      "url": "https://juribuora.github.io/blog/2026/04/30/day-89.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "tcpip",
        "learningprocess"
      ],
      "slug": "day-89",
      "sourcePath": "Blog/_posts/2026-04-30-day-89.md",
      "contentPath": "/generated/posts/blog/89.json"
    },
    {
      "day": 88,
      "title": "Security Design Principles and OAuth",
      "date": "2026-04-29",
      "url": "https://juribuora.github.io/blog/2026/04/29/day-88.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "learningprocess"
      ],
      "slug": "day-88",
      "sourcePath": "Blog/_posts/2026-04-29-day-88.md",
      "contentPath": "/generated/posts/blog/88.json"
    },
    {
      "day": 87,
      "title": "Network Protocols, Ports, and SOC Visibility",
      "date": "2026-04-28",
      "url": "https://juribuora.github.io/blog/2026/04/28/day-87.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "tcpip",
        "dns",
        "learningprocess"
      ],
      "slug": "day-87",
      "sourcePath": "Blog/_posts/2026-04-28-day-87.md",
      "contentPath": "/generated/posts/blog/87.json"
    },
    {
      "day": 86,
      "title": "Investigating Botnets and IoT Malware",
      "date": "2026-04-27",
      "url": "https://juribuora.github.io/blog/2026/04/27/day-86.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "learningprocess"
      ],
      "slug": "day-86",
      "sourcePath": "Blog/_posts/2026-04-27-day-86.md",
      "contentPath": "/generated/posts/blog/86.json"
    },
    {
      "day": 85,
      "title": "Understanding Cryptomining Malware",
      "date": "2026-04-26",
      "url": "https://juribuora.github.io/blog/2026/04/26/day-85.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "processes",
        "learningprocess"
      ],
      "slug": "day-85",
      "sourcePath": "Blog/_posts/2026-04-26-day-85.md",
      "contentPath": "/generated/posts/blog/85.json"
    },
    {
      "day": 84,
      "title": "Lateral Movement Techniques in Enterprise Networks",
      "date": "2026-04-25",
      "url": "https://juribuora.github.io/blog/2026/04/25/day-84.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "processes",
        "learningprocess"
      ],
      "slug": "day-84",
      "sourcePath": "Blog/_posts/2026-04-25-day-84.md",
      "contentPath": "/generated/posts/blog/84.json"
    },
    {
      "day": 83,
      "title": "The Colonial Pipeline Ransomware Incident",
      "date": "2026-04-24",
      "url": "https://juribuora.github.io/blog/2026/04/24/day-83.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-83",
      "sourcePath": "Blog/_posts/2026-04-24-day-83.md",
      "contentPath": "/generated/posts/blog/83.json"
    },
    {
      "day": 82,
      "title": "The NotPetya Cyberweapon and Destructive Malware",
      "date": "2026-04-23",
      "url": "https://juribuora.github.io/blog/2026/04/23/day-82.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "learningprocess"
      ],
      "slug": "day-82",
      "sourcePath": "Blog/_posts/2026-04-23-day-82.md",
      "contentPath": "/generated/posts/blog/82.json"
    },
    {
      "day": 81,
      "title": "The WannaCry Global Ransomware Outbreak",
      "date": "2026-04-22",
      "url": "https://juribuora.github.io/blog/2026/04/22/day-81.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "learningprocess"
      ],
      "slug": "day-81",
      "sourcePath": "Blog/_posts/2026-04-22-day-81.md",
      "contentPath": "/generated/posts/blog/81.json"
    },
    {
      "day": 80,
      "title": "Understanding Ransomware Attacks",
      "date": "2026-04-21",
      "url": "https://juribuora.github.io/blog/2026/04/21/day-80.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-80",
      "sourcePath": "Blog/_posts/2026-04-21-day-80.md",
      "contentPath": "/generated/posts/blog/80.json"
    },
    {
      "day": 79,
      "title": "Squiblydoo and Rundll32 Script Execution",
      "date": "2026-04-20",
      "url": "https://juribuora.github.io/blog/2026/04/20/day-79.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "processes",
        "learningprocess"
      ],
      "slug": "day-79",
      "sourcePath": "Blog/_posts/2026-04-20-day-79.md",
      "contentPath": "/generated/posts/blog/79.json"
    },
    {
      "day": 78,
      "title": "Metasploit and Exploitation Frameworks",
      "date": "2026-04-19",
      "url": "https://juribuora.github.io/blog/2026/04/19/day-78.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-78",
      "sourcePath": "Blog/_posts/2026-04-19-day-78.md",
      "contentPath": "/generated/posts/blog/78.json"
    },
    {
      "day": 77,
      "title": "PowerShell Empire and Fileless Malware Techniques",
      "date": "2026-04-18",
      "url": "https://juribuora.github.io/blog/2026/04/18/day-77.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "processes",
        "learningprocess"
      ],
      "slug": "day-77",
      "sourcePath": "Blog/_posts/2026-04-18-day-77.md",
      "contentPath": "/generated/posts/blog/77.json"
    },
    {
      "day": 76,
      "title": "Understanding Cobalt Strike and Post-Exploitation Frameworks",
      "date": "2026-04-17",
      "url": "https://juribuora.github.io/blog/2026/04/17/day-76.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-76",
      "sourcePath": "Blog/_posts/2026-04-17-day-76.md",
      "contentPath": "/generated/posts/blog/76.json"
    },
    {
      "day": 75,
      "title": "Understanding Fail2Ban and Automated Defense",
      "date": "2026-04-16",
      "url": "https://juribuora.github.io/blog/2026/04/16/day-75.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "defense",
        "learningprocess"
      ],
      "slug": "day-75",
      "sourcePath": "Blog/_posts/2026-04-16-day-75.md",
      "contentPath": "/generated/posts/blog/75.json"
    },
    {
      "day": 74,
      "title": "Turning Raw Logs into Patterns and Evidence",
      "date": "2026-04-15",
      "url": "https://juribuora.github.io/blog/2026/04/15/day-74.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "logs",
        "learningprocess"
      ],
      "slug": "day-74",
      "sourcePath": "Blog/_posts/2026-04-15-day-74.md",
      "contentPath": "/generated/posts/blog/74.json"
    },
    {
      "day": 73,
      "title": "Detecting SSH Brute Force Attacks Using auth.log",
      "date": "2026-04-14",
      "url": "https://juribuora.github.io/blog/2026/04/14/day-73.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "logs",
        "ssh",
        "learningprocess"
      ],
      "slug": "day-73",
      "sourcePath": "Blog/_posts/2026-04-14-day-73.md",
      "contentPath": "/generated/posts/blog/73.json"
    },
    {
      "day": 72,
      "title": "From Commands to Systems Thinking in Cybersecurity",
      "date": "2026-04-13",
      "url": "https://juribuora.github.io/blog/2026/04/13/day-72.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-72",
      "sourcePath": "Blog/_posts/2026-04-13-day-72.md",
      "contentPath": "/generated/posts/blog/72.json"
    },
    {
      "day": 71,
      "title": "Verifying Services and Understanding Why Connections Fail",
      "date": "2026-04-12",
      "url": "https://juribuora.github.io/blog/2026/04/12/day-71.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "networking",
        "learningprocess"
      ],
      "slug": "day-71",
      "sourcePath": "Blog/_posts/2026-04-12-day-71.md",
      "contentPath": "/generated/posts/blog/71.json"
    },
    {
      "day": 70,
      "title": "Mapping IP Addresses to Devices Using ARP",
      "date": "2026-04-11",
      "url": "https://juribuora.github.io/blog/2026/04/11/day-70.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "learningprocess"
      ],
      "slug": "day-70",
      "sourcePath": "Blog/_posts/2026-04-11-day-70.md",
      "contentPath": "/generated/posts/blog/70.json"
    },
    {
      "day": 69,
      "title": "Understanding NAT vs Bridged Networking in a Lab Environment",
      "date": "2026-04-10",
      "url": "https://juribuora.github.io/blog/2026/04/10/day-69.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "labs",
        "learningprocess"
      ],
      "slug": "day-69",
      "sourcePath": "Blog/_posts/2026-04-10-day-69.md",
      "contentPath": "/generated/posts/blog/69.json"
    },
    {
      "day": 68,
      "title": "Testing Network Connectivity and Verifying Open Ports",
      "date": "2026-04-09",
      "url": "https://juribuora.github.io/blog/2026/04/09/day-68.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "linux",
        "learningprocess"
      ],
      "slug": "day-68",
      "sourcePath": "Blog/_posts/2026-04-09-day-68.md",
      "contentPath": "/generated/posts/blog/68.json"
    },
    {
      "day": 67,
      "title": "Investigating SSH Connection Failures and Security Warnings",
      "date": "2026-04-08",
      "url": "https://juribuora.github.io/blog/2026/04/08/day-67.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "networking",
        "ssh",
        "learningprocess"
      ],
      "slug": "day-67",
      "sourcePath": "Blog/_posts/2026-04-08-day-67.md",
      "contentPath": "/generated/posts/blog/67.json"
    },
    {
      "day": 66,
      "title": "Debugging DNS Resolution and Understanding Hosting Mismatch",
      "date": "2026-04-07",
      "url": "https://juribuora.github.io/blog/2026/04/07/day-66.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "githubpages",
        "learningprocess"
      ],
      "slug": "day-66",
      "sourcePath": "Blog/_posts/2026-04-07-day-66.md",
      "contentPath": "/generated/posts/blog/66.json"
    },
    {
      "day": 65,
      "title": "Understanding GitHub Authentication, Cloning, and Local Repositories",
      "date": "2026-04-06",
      "url": "https://juribuora.github.io/blog/2026/04/06/day-65.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "githubpages",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-65",
      "sourcePath": "Blog/_posts/2026-04-06-day-65.md",
      "contentPath": "/generated/posts/blog/65.json"
    },
    {
      "day": 64,
      "title": "AI Agents, Model Context Protocol (MCP), and Security Implications",
      "date": "2026-04-05",
      "url": "https://juribuora.github.io/blog/2026/04/05/day-64.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "learningprocess"
      ],
      "slug": "day-64",
      "sourcePath": "Blog/_posts/2026-04-05-day-64.md",
      "contentPath": "/generated/posts/blog/64.json"
    },
    {
      "day": 63,
      "title": "Understanding Local LLM Infrastructure and Model Quantization",
      "date": "2026-04-04",
      "url": "https://juribuora.github.io/blog/2026/04/04/day-63.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "learningprocess"
      ],
      "slug": "day-63",
      "sourcePath": "Blog/_posts/2026-04-04-day-63.md",
      "contentPath": "/generated/posts/blog/63.json"
    },
    {
      "day": 62,
      "title": "Understanding Phishing Attacks and Email Security Controls",
      "date": "2026-04-03",
      "url": "https://juribuora.github.io/blog/2026/04/03/day-62.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "webfundamentals",
        "learningprocess"
      ],
      "slug": "day-62",
      "sourcePath": "Blog/_posts/2026-04-03-day-62.md",
      "contentPath": "/generated/posts/blog/62.json"
    },
    {
      "day": 61,
      "title": "Investigating the Dark Web Safely and Understanding Tor",
      "date": "2026-04-02",
      "url": "https://juribuora.github.io/blog/2026/04/02/day-61.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "learningprocess"
      ],
      "slug": "day-61",
      "sourcePath": "Blog/_posts/2026-04-02-day-61.md",
      "contentPath": "/generated/posts/blog/61.json"
    },
    {
      "day": 60,
      "title": "Understanding Local AI, Model Hosting, and the Cloud vs Local Debate",
      "date": "2026-04-01",
      "url": "https://juribuora.github.io/blog/2026/04/01/day-60.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "networking",
        "learningprocess"
      ],
      "slug": "day-60",
      "sourcePath": "Blog/_posts/2026-04-01-day-60.md",
      "contentPath": "/generated/posts/blog/60.json"
    },
    {
      "day": 59,
      "title": "Studying Malware Families: TrickBot, WannaMine and Cryptomining Threats",
      "date": "2026-03-31",
      "url": "https://juribuora.github.io/blog/2026/03/31/day-59.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-59",
      "sourcePath": "Blog/_posts/2026-03-31-day-59.md",
      "contentPath": "/generated/posts/blog/59.json"
    },
    {
      "day": 58,
      "title": "DLL Files, Code Signing, and Malware Trust Verification",
      "date": "2026-03-30",
      "url": "https://juribuora.github.io/blog/2026/03/30/day-58.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "windows",
        "learningprocess"
      ],
      "slug": "day-58",
      "sourcePath": "Blog/_posts/2026-03-30-day-58.md",
      "contentPath": "/generated/posts/blog/58.json"
    },
    {
      "day": 57,
      "title": "LOLBins Deep Dive: Squiblydoo (rundll32 and mshtml Abuse)",
      "date": "2026-03-29",
      "url": "https://juribuora.github.io/blog/2026/03/29/day-57.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "windows",
        "learningprocess"
      ],
      "slug": "day-57",
      "sourcePath": "Blog/_posts/2026-03-29-day-57.md",
      "contentPath": "/generated/posts/blog/57.json"
    },
    {
      "day": 56,
      "title": "Offensive Security Frameworks and LOLBins",
      "date": "2026-03-28",
      "url": "https://juribuora.github.io/blog/2026/03/28/day-56.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-56",
      "sourcePath": "Blog/_posts/2026-03-28-day-56.md",
      "contentPath": "/generated/posts/blog/56.json"
    },
    {
      "day": 55,
      "title": "Typosquatting and Malicious Domain Impersonation",
      "date": "2026-03-27",
      "url": "https://juribuora.github.io/blog/2026/03/27/day-55.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "learningprocess"
      ],
      "slug": "day-55",
      "sourcePath": "Blog/_posts/2026-03-27-day-55.md",
      "contentPath": "/generated/posts/blog/55.json"
    },
    {
      "day": 54,
      "title": "Investigating Phishing Through Email Gateway Logs",
      "date": "2026-03-26",
      "url": "https://juribuora.github.io/blog/2026/03/26/day-54.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "networking",
        "learningprocess"
      ],
      "slug": "day-54",
      "sourcePath": "Blog/_posts/2026-03-26-day-54.md",
      "contentPath": "/generated/posts/blog/54.json"
    },
    {
      "day": 53,
      "title": "Understanding Phishing Attacks and Email Security Layers",
      "date": "2026-03-25",
      "url": "https://juribuora.github.io/blog/2026/03/25/day-53.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "webfundamentals",
        "networking",
        "learningprocess"
      ],
      "slug": "day-53",
      "sourcePath": "Blog/_posts/2026-03-25-day-53.md",
      "contentPath": "/generated/posts/blog/53.json"
    },
    {
      "day": 52,
      "title": "First Steps with Python and JavaScript for Security",
      "date": "2026-03-24",
      "url": "https://juribuora.github.io/blog/2026/03/24/day-52.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "tryhackme",
        "learningprocess"
      ],
      "slug": "day-52",
      "sourcePath": "Blog/_posts/2026-03-24-day-52.md",
      "contentPath": "/generated/posts/blog/52.json"
    },
    {
      "day": 51,
      "title": "CLI Fundamentals, OS Security, and Understanding How Data is Represented",
      "date": "2026-03-23",
      "url": "https://juribuora.github.io/blog/2026/03/23/day-51.html",
      "category": "blog",
      "tags": [
        "linux",
        "commandline",
        "webfundamentals",
        "tryhackme",
        "learningprocess"
      ],
      "slug": "day-51",
      "sourcePath": "Blog/_posts/2026-03-23-day-51.md",
      "contentPath": "/generated/posts/blog/51.json"
    },
    {
      "day": 50,
      "title": "Understanding Advanced Persistent Threat (APT) Groups",
      "date": "2026-03-22",
      "url": "https://juribuora.github.io/blog/2026/03/22/day-50.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-50",
      "sourcePath": "Blog/_posts/2026-03-22-day-50.md",
      "contentPath": "/generated/posts/blog/50.json"
    },
    {
      "day": 49,
      "title": "Investigating Phishing Infrastructure and Email Attacks",
      "date": "2026-03-21",
      "url": "https://juribuora.github.io/blog/2026/03/21/day-49.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-49",
      "sourcePath": "Blog/_posts/2026-03-21-day-49.md",
      "contentPath": "/generated/posts/blog/49.json"
    },
    {
      "day": 48,
      "title": "Detecting Authentication Attacks in System Logs",
      "date": "2026-03-20",
      "url": "https://juribuora.github.io/blog/2026/03/20/day-48.html",
      "category": "blog",
      "tags": [
        "logs",
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-48",
      "sourcePath": "Blog/_posts/2026-03-20-day-48.md",
      "contentPath": "/generated/posts/blog/48.json"
    },
    {
      "day": 47,
      "title": "Encoded PowerShell and Obfuscated Command Execution",
      "date": "2026-03-19",
      "url": "https://juribuora.github.io/blog/2026/03/19/day-47.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "processes",
        "learningprocess"
      ],
      "slug": "day-47",
      "sourcePath": "Blog/_posts/2026-03-19-day-47.md",
      "contentPath": "/generated/posts/blog/47.json"
    },
    {
      "day": 46,
      "title": "Understanding LOLBins and Living-off-the-Land Attacks",
      "date": "2026-03-18",
      "url": "https://juribuora.github.io/blog/2026/03/18/day-46.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "processes",
        "learningprocess"
      ],
      "slug": "day-46",
      "sourcePath": "Blog/_posts/2026-03-18-day-46.md",
      "contentPath": "/generated/posts/blog/46.json"
    },
    {
      "day": 45,
      "title": "Pivot Training for Log Investigation",
      "date": "2026-03-17",
      "url": "https://juribuora.github.io/blog/2026/03/17/day-45.html",
      "category": "blog",
      "tags": [
        "logs",
        "commandline",
        "learningprocess",
        "cybersecurity"
      ],
      "slug": "day-45",
      "sourcePath": "Blog/_posts/2026-03-17-day-45.md",
      "contentPath": "/generated/posts/blog/45.json"
    },
    {
      "day": 44,
      "title": "Detecting Beaconing and Command-and-Control Traffic",
      "date": "2026-03-16",
      "url": "https://juribuora.github.io/blog/2026/03/16/day-44.html",
      "category": "blog",
      "tags": [
        "logs",
        "networking",
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-44",
      "sourcePath": "Blog/_posts/2026-03-16-day-44.md",
      "contentPath": "/generated/posts/blog/44.json"
    },
    {
      "day": 43,
      "title": "Detecting Suspicious Process Chains",
      "date": "2026-03-15",
      "url": "https://juribuora.github.io/blog/2026/03/15/day-43.html",
      "category": "blog",
      "tags": [
        "processes",
        "logs",
        "cybersecurity",
        "learningprocess"
      ],
      "slug": "day-43",
      "sourcePath": "Blog/_posts/2026-03-15-day-43.md",
      "contentPath": "/generated/posts/blog/43.json"
    },
    {
      "day": 42,
      "title": "SOC Thinking: Turning Logs into Evidence",
      "date": "2026-03-14",
      "url": "https://juribuora.github.io/blog/2026/03/14/day-42.html",
      "category": "blog",
      "tags": [
        "logs",
        "commandline",
        "learningprocess",
        "cybersecurity"
      ],
      "slug": "day-42",
      "sourcePath": "Blog/_posts/2026-03-14-day-42.md",
      "contentPath": "/generated/posts/blog/42.json"
    },
    {
      "day": 41,
      "title": "Sysmon Telemetry, Lab Automation, and Full Cyber Lab Architecture",
      "date": "2026-03-13",
      "url": "https://juribuora.github.io/blog/2026/03/13/day-41.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "windows",
        "logs",
        "processes",
        "commandline",
        "learningprocess"
      ],
      "slug": "day-41",
      "sourcePath": "Blog/_posts/2026-03-13-day-41.md",
      "contentPath": "/generated/posts/blog/41.json"
    },
    {
      "day": 40,
      "title": "Building a Reproducible Windows SOC VM and Lab Infrastructure",
      "date": "2026-03-12",
      "url": "https://juribuora.github.io/blog/2026/03/12/day-40.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "windows",
        "processes",
        "logs",
        "commandline",
        "learningprocess"
      ],
      "slug": "day-40",
      "sourcePath": "Blog/_posts/2026-03-12-day-40.md",
      "contentPath": "/generated/posts/blog/40.json"
    },
    {
      "day": 39,
      "title": "Building a Portable Zsh Environment with GitHub Dotfiles",
      "date": "2026-03-11",
      "url": "https://juribuora.github.io/blog/2026/03/11/day-39.html",
      "category": "blog",
      "tags": [
        "linux",
        "commandline",
        "bash",
        "githubpages",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-39",
      "sourcePath": "Blog/_posts/2026-03-11-day-39.md",
      "contentPath": "/generated/posts/blog/39.json"
    },
    {
      "day": 38,
      "title": "SSH Brute-Force Investigation and Automated Defense",
      "date": "2026-03-10",
      "url": "https://juribuora.github.io/blog/2026/03/10/day-38.html",
      "category": "blog",
      "tags": [
        "linux",
        "commandline",
        "logs",
        "ssh",
        "networking"
      ],
      "slug": "day-38",
      "sourcePath": "Blog/_posts/2026-03-10-day-38.md",
      "contentPath": "/generated/posts/blog/38.json"
    },
    {
      "day": 37,
      "title": "Ports, Services, and Investigating Listening Processes",
      "date": "2026-03-09",
      "url": "https://juribuora.github.io/blog/2026/03/09/day-37.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "networking",
        "processes",
        "labs",
        "learningprocess"
      ],
      "slug": "day-37",
      "sourcePath": "Blog/_posts/2026-03-09-day-37.md",
      "contentPath": "/generated/posts/blog/37.json"
    },
    {
      "day": 36,
      "title": "Linux Process Investigation and First Log Exploration",
      "date": "2026-03-07",
      "url": "https://juribuora.github.io/blog/2026/03/07/day-36.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "processes",
        "logs",
        "learningprocess",
        "labs"
      ],
      "slug": "day-36",
      "sourcePath": "Blog/_posts/2026-03-07-day-36.md",
      "contentPath": "/generated/posts/blog/36.json"
    },
    {
      "day": 35,
      "title": "Linux Process Baselining with ps and top",
      "date": "2026-03-05",
      "url": "https://juribuora.github.io/blog/2026/03/05/day-35.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "processes",
        "cybersecurity",
        "learningprocess",
        "labs"
      ],
      "slug": "day-35",
      "sourcePath": "Blog/_posts/2026-03-05-day-35.md",
      "contentPath": "/generated/posts/blog/35.json"
    },
    {
      "day": 34,
      "title": "Networking Mental Model Reset (DNS, TCP/UDP, HTTPS/TLS, QUIC)",
      "date": "2026-03-03",
      "url": "https://juribuora.github.io/blog/2026/03/03/day-34.html",
      "category": "blog",
      "tags": [
        "networking",
        "tcpip",
        "dns",
        "http",
        "webfundamentals",
        "learningprocess",
        "labs"
      ],
      "slug": "day-34",
      "sourcePath": "Blog/_posts/2026-03-03-day-34.md",
      "contentPath": "/generated/posts/blog/34.json"
    },
    {
      "day": 33,
      "title": "Expanding the SOC Learning Roadmap (Identity, Triage, and Hiring Readiness)",
      "date": "2026-03-02",
      "url": "https://juribuora.github.io/blog/2026/03/02/day-33.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "learningprocess",
        "documentation",
        "tooling"
      ],
      "slug": "day-33",
      "sourcePath": "Blog/_posts/2026-03-02-day-33.md",
      "contentPath": "/generated/posts/blog/33.json"
    },
    {
      "day": 32,
      "title": "OSI Model, Encapsulation, and Core Network Protocols",
      "date": "2026-03-01",
      "url": "https://juribuora.github.io/blog/2026/03/01/day-32.html",
      "category": "blog",
      "tags": [
        "networking",
        "tcpip",
        "cybersecurity",
        "foundations",
        "learningprocess"
      ],
      "slug": "day-32",
      "sourcePath": "Blog/_posts/2026-03-01-day-32.md",
      "contentPath": "/generated/posts/blog/32.json"
    },
    {
      "day": 31,
      "title": "Regex Behavior and Text Processing Foundations",
      "date": "2026-02-28",
      "url": "https://juribuora.github.io/blog/2026/02/28/day-31.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "bash",
        "webfundamentals",
        "learningprocess"
      ],
      "slug": "day-31",
      "sourcePath": "Blog/_posts/2026-02-28-day-31.md",
      "contentPath": "/generated/posts/blog/31.json"
    },
    {
      "day": 30,
      "title": "Streams, Exit Codes, and Bash Redirection",
      "date": "2026-02-27",
      "url": "https://juribuora.github.io/blog/2026/02/27/day-30.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "bash",
        "processes",
        "learningprocess"
      ],
      "slug": "day-30",
      "sourcePath": "Blog/_posts/2026-02-27-day-30.md",
      "contentPath": "/generated/posts/blog/30.json"
    },
    {
      "day": 29,
      "title": "SOC Thinking with Linux Pipelines, Pivots, and Process Chains",
      "date": "2026-02-26",
      "url": "https://juribuora.github.io/blog/2026/02/26/day-29.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linuxfundamentals",
        "commandline",
        "bash",
        "processes",
        "logs",
        "labs",
        "learningprocess"
      ],
      "slug": "day-29",
      "sourcePath": "Blog/_posts/2026-02-26-day-29.md",
      "contentPath": "/generated/posts/blog/29.json"
    },
    {
      "day": 28,
      "title": "Understanding Command Resolution & Filesystem Investigation with find",
      "date": "2026-02-25",
      "url": "https://juribuora.github.io/blog/2026/02/25/day-28.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "bash",
        "filesystem",
        "permissions",
        "processes",
        "learningprocess"
      ],
      "slug": "day-28",
      "sourcePath": "Blog/_posts/2026-02-25-day-28.md",
      "contentPath": "/generated/posts/blog/28.json"
    },
    {
      "day": 27,
      "title": "Command Resolution, PATH Internals & Shell Environment Investigation",
      "date": "2026-02-24",
      "url": "https://juribuora.github.io/blog/2026/02/24/day-27.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "bash",
        "filesystem",
        "learningprocess"
      ],
      "slug": "day-27",
      "sourcePath": "Blog/_posts/2026-02-24-day-27.md",
      "contentPath": "/generated/posts/blog/27.json"
    },
    {
      "day": 26,
      "title": "Effective Shell Part 2: Pipelines, Readline Search, Job Control",
      "date": "2026-02-22",
      "url": "https://juribuora.github.io/blog/2026/02/22/day-26.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "bash",
        "processes",
        "labs",
        "learningprocess"
      ],
      "slug": "day-26",
      "sourcePath": "Blog/_posts/2026-02-22-day-26.md",
      "contentPath": "/generated/posts/blog/26.json"
    },
    {
      "day": 25,
      "title": "Effective Shell Fundamentals: ls, du, man, Heredocs, Updates, and Docker Permissions",
      "date": "2026-02-18",
      "url": "https://juribuora.github.io/blog/2026/02/18/day-25.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linuxfundamentals",
        "commandline",
        "bash",
        "filesystem",
        "permissions",
        "processes",
        "logs",
        "learningprocess"
      ],
      "slug": "day-25",
      "sourcePath": "Blog/_posts/2026-02-18-day-25.md",
      "contentPath": "/generated/posts/blog/25.json"
    },
    {
      "day": 24,
      "title": "Tools Lane Setup, Effective Shell, and Shutdown Triage",
      "date": "2026-02-17",
      "url": "https://juribuora.github.io/blog/2026/02/17/day-24.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "bash",
        "filesystem",
        "processes",
        "logs",
        "learningprocess"
      ],
      "slug": "day-24",
      "sourcePath": "Blog/_posts/2026-02-17-day-24.md",
      "contentPath": "/generated/posts/blog/24.json"
    },
    {
      "day": 23,
      "title": "Consolidation, Repetition, and Anki-Driven Recall",
      "date": "2026-02-15",
      "url": "https://juribuora.github.io/blog/2026/02/15/day-23.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "bash",
        "learningprocess"
      ],
      "slug": "day-23",
      "sourcePath": "Blog/_posts/2026-02-15-day-23.md",
      "contentPath": "/generated/posts/blog/23.json"
    },
    {
      "day": 22,
      "title": "stdout, stderr, wget, and Output Validation",
      "date": "2026-02-14",
      "url": "https://juribuora.github.io/blog/2026/02/14/day-22.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "commandline",
        "bash",
        "learningprocess"
      ],
      "slug": "day-22",
      "sourcePath": "Blog/_posts/2026-02-14-day-22.md",
      "contentPath": "/generated/posts/blog/22.json"
    },
    {
      "day": 21,
      "title": "Building My Detection Engineering Repo + Hardening My Blog Setup",
      "date": "2026-02-13",
      "url": "https://juribuora.github.io/blog/2026/02/13/day-21.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "logs",
        "linux",
        "commandline",
        "githubpages",
        "jekyll",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-21",
      "sourcePath": "Blog/_posts/2026-02-13-day-21.md",
      "contentPath": "/generated/posts/blog/21.json"
    },
    {
      "day": 20,
      "title": "Auditing a Media Archive and Taking Control of Backups",
      "date": "2026-02-12",
      "url": "https://juribuora.github.io/blog/2026/02/12/day-20.html",
      "category": "blog",
      "tags": [
        "commandline",
        "filesystem",
        "logs",
        "tooling",
        "documentation",
        "learningprocess"
      ],
      "slug": "day-20",
      "sourcePath": "Blog/_posts/2026-02-12-day-20.md",
      "contentPath": "/generated/posts/blog/20.json"
    },
    {
      "day": 19,
      "title": "Bare-Metal Dual Boot on Intel Mac (macOS + Ubuntu Server)",
      "date": "2026-02-11",
      "url": "https://juribuora.github.io/blog/2026/02/11/day-19.html",
      "category": "blog",
      "tags": [
        "linux",
        "linuxfundamentals",
        "filesystem",
        "permissions",
        "ssh",
        "labs",
        "learningprocess"
      ],
      "slug": "day-19",
      "sourcePath": "Blog/_posts/2026-02-11-day-19.md",
      "contentPath": "/generated/posts/blog/19.json"
    },
    {
      "day": 18,
      "title": "Intel Mac Dual-Boot Experiments, Architecture Friction, and Lab Prep",
      "date": "2026-02-10",
      "url": "https://juribuora.github.io/blog/2026/02/10/day-18.html",
      "category": "blog",
      "tags": [
        "linux",
        "linuxfundamentals",
        "cybersecurity",
        "tooling",
        "learningprocess"
      ],
      "slug": "day-18",
      "sourcePath": "Blog/_posts/2026-02-10-day-18.md",
      "contentPath": "/generated/posts/blog/18.json"
    },
    {
      "day": 17,
      "title": "Cookies, Sessions, and Trust Boundaries",
      "date": "2026-02-08",
      "url": "https://juribuora.github.io/blog/2026/02/08/day-17.html",
      "category": "blog",
      "tags": [
        "foundations",
        "cybersecurity",
        "webfundamentals",
        "http",
        "labs",
        "learningprocess"
      ],
      "slug": "day-17",
      "sourcePath": "Blog/_posts/2026-02-08-day-17.md",
      "contentPath": "/generated/posts/blog/17.json"
    },
    {
      "day": 16,
      "title": "Linux Privilege Escalation: SUID, SGID, Sticky Bit (Foundations)",
      "date": "2026-02-07",
      "url": "https://juribuora.github.io/blog/2026/02/07/day-16.html",
      "category": "blog",
      "tags": [
        "linux",
        "permissions",
        "processes",
        "linuxfundamentals",
        "cybersecurity",
        "labs"
      ],
      "slug": "day-16",
      "sourcePath": "Blog/_posts/2026-02-07-day-16.md",
      "contentPath": "/generated/posts/blog/16.json"
    },
    {
      "day": 15,
      "title": "Building a Proper Terminal Logging Pipeline",
      "date": "2026-02-06",
      "url": "https://juribuora.github.io/blog/2026/02/06/day-15.html",
      "category": "blog",
      "tags": [
        "linux",
        "commandline",
        "bash",
        "logs",
        "labs",
        "learningprocess"
      ],
      "slug": "day-15",
      "sourcePath": "Blog/_posts/2026-02-06-day-15.md",
      "contentPath": "/generated/posts/blog/15.json"
    },
    {
      "day": 14,
      "title": "Linux Permissions, Identity, Pipes, and Data Processing Fundamentals",
      "date": "2026-02-05",
      "url": "https://juribuora.github.io/blog/2026/02/05/day-14.html",
      "category": "blog",
      "tags": [
        "linuxfundamentals",
        "linux",
        "commandline",
        "permissions",
        "filesystem",
        "processes",
        "logs",
        "bash",
        "ssh",
        "learningprocess"
      ],
      "slug": "day-14",
      "sourcePath": "Blog/_posts/2026-02-05-day-14.md",
      "contentPath": "/generated/posts/blog/14.json"
    },
    {
      "day": 13,
      "title": "SSH and Networking Flow Between VMs",
      "date": "2026-02-04",
      "url": "https://juribuora.github.io/blog/2026/02/04/day-13.html",
      "category": "blog",
      "tags": [
        "linux",
        "networking",
        "commandline",
        "ssh",
        "learningprocess"
      ],
      "slug": "day-13",
      "sourcePath": "Blog/_posts/2026-02-04-day-13.md",
      "contentPath": "/generated/posts/blog/13.json"
    },
    {
      "day": 12,
      "title": "Linux Files, Permissions, and Safety",
      "date": "2026-02-02",
      "url": "https://juribuora.github.io/blog/2026/02/02/day-12.html",
      "category": "blog",
      "tags": [
        "linux",
        "commandline",
        "filesystem",
        "permissions",
        "logs",
        "learningprocess"
      ],
      "slug": "day-12",
      "sourcePath": "Blog/_posts/2026-02-02-day-12.md",
      "contentPath": "/generated/posts/blog/12.json"
    },
    {
      "day": 11,
      "title": "Linux Fundamentals Part 3 (Finale)",
      "date": "2026-01-31",
      "url": "https://juribuora.github.io/blog/2026/01/31/day-11.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "linuxfundamentals",
        "processes",
        "automation",
        "cron",
        "packagemanagement",
        "logs",
        "ssh",
        "networking",
        "tryhackme"
      ],
      "slug": "day-11",
      "sourcePath": "Blog/_posts/2026-01-31-day-11.md",
      "contentPath": "/generated/posts/blog/11.json"
    },
    {
      "day": 10,
      "title": "Linux Fundamentals Part 2 (SSH, Filesystem, Permissions)",
      "date": "2026-01-30",
      "url": "https://juribuora.github.io/blog/2026/01/30/day-10.html",
      "category": "blog",
      "tags": [
        "cybersecurity",
        "linux",
        "linuxfundamentals",
        "commandline",
        "bash",
        "ssh",
        "filepermissions",
        "tryhackme",
        "cybersecurityfoundations"
      ],
      "slug": "day-10",
      "sourcePath": "Blog/_posts/2026-01-30-day-10.md",
      "contentPath": "/generated/posts/blog/10.json"
    },
    {
      "day": 9,
      "title": "Linux Fundamentals Part 1",
      "date": "2026-01-27",
      "url": "https://juribuora.github.io/blog/2026/01/27/day-09.html",
      "category": "blog",
      "tags": [
        "linux",
        "linuxfundamentals",
        "commandline",
        "bash",
        "filesystem",
        "grep",
        "tryhackme",
        "cybersecurityfoundations"
      ],
      "slug": "day-09",
      "sourcePath": "Blog/_posts/2026-01-27-day-09.md",
      "contentPath": "/generated/posts/blog/9.json"
    },
    {
      "day": 8,
      "title": "Killing Minima Ghosts & Owning the Stack",
      "date": "2026-01-26",
      "url": "https://juribuora.github.io/blog/2026/01/26/day-08.html",
      "category": "blog",
      "tags": [
        "jekyll",
        "githubpages",
        "staticsite",
        "css",
        "debugging",
        "tooling",
        "rss",
        "webfundamentals"
      ],
      "slug": "day-08",
      "sourcePath": "Blog/_posts/2026-01-26-day-08.md",
      "contentPath": "/generated/posts/blog/8.json"
    },
    {
      "day": 7,
      "title": "Workflow Ergonomics & GitHub Pages Stabilization",
      "date": "2026-01-25",
      "url": "https://juribuora.github.io/blog/2026/01/25/day-07.html",
      "category": "blog",
      "tags": [
        "workflow",
        "macos",
        "linuxux",
        "githubpages",
        "jekyll",
        "staticsites",
        "tooling",
        "documentation"
      ],
      "slug": "day-07",
      "sourcePath": "Blog/_posts/2026-01-25-day-07.md",
      "contentPath": "/generated/posts/blog/7.json"
    },
    {
      "day": 6,
      "title": "Polishing Website & Fixing Jekyll Environment",
      "date": "2026-01-24",
      "url": "https://juribuora.github.io/blog/2026/01/24/day-06.html",
      "category": "blog",
      "tags": [
        "jekyll",
        "githubpages",
        "vscode",
        "ruby",
        "rbenv",
        "homebrew",
        "websitemaintenance",
        "blogging",
        "troubleshooting"
      ],
      "slug": "day-06",
      "sourcePath": "Blog/_posts/2026-01-24-day-06.md",
      "contentPath": "/generated/posts/blog/6.json"
    },
    {
      "day": 5,
      "title": "Blogging with GitHub Pages (Publishing Foundations)",
      "date": "2026-01-23",
      "url": "https://juribuora.github.io/blog/2026/01/23/day-05.html",
      "category": "blog",
      "tags": [
        "githubpages",
        "jekyll",
        "blogging",
        "documentation",
        "vscode",
        "github",
        "learninginpublic"
      ],
      "slug": "day-05",
      "sourcePath": "Blog/_posts/2026-01-23-day-05.md",
      "contentPath": "/generated/posts/blog/5.json"
    },
    {
      "day": 4,
      "title": "Recovery Day Logged Honestly",
      "date": "2026-01-22",
      "url": "https://juribuora.github.io/blog/2026/01/22/day-04.html",
      "category": "blog",
      "tags": [
        "dailylog",
        "zeroday",
        "consistency",
        "learningprocess"
      ],
      "slug": "day-04",
      "sourcePath": "Blog/_posts/2026-01-22-day-04.md",
      "contentPath": "/generated/posts/blog/4.json"
    },
    {
      "day": 3,
      "title": "How Websites Work (Big Picture)",
      "date": "2026-01-21",
      "url": "https://juribuora.github.io/blog/2026/01/21/day-03.html",
      "category": "blog",
      "tags": [
        "webfundamentals",
        "dns",
        "http",
        "networking",
        "visualization",
        "tryhackme",
        "cybersecurity"
      ],
      "slug": "day-03",
      "sourcePath": "Blog/_posts/2026-01-21-day-03.md",
      "contentPath": "/generated/posts/blog/3.json"
    },
    {
      "day": 2,
      "title": "Networking & Web Fundamentals (Consolidation Day)",
      "date": "2026-01-20",
      "url": "https://juribuora.github.io/blog/2026/01/20/day-02.html",
      "category": "blog",
      "tags": [
        "tryhackme",
        "networking",
        "dns",
        "http",
        "packets",
        "obsidian",
        "parallels",
        "cybersecurity"
      ],
      "slug": "day-02",
      "sourcePath": "Blog/_posts/2026-01-20-day-02.md",
      "contentPath": "/generated/posts/blog/2.json"
    },
    {
      "day": 1,
      "title": "Environment Setup & Foundations",
      "date": "2026-01-19",
      "url": "https://juribuora.github.io/blog/2026/01/19/day-01.html",
      "category": "blog",
      "tags": [
        "virtualmachine",
        "parallels",
        "macbook",
        "windows11",
        "kalilinux",
        "ubuntu",
        "obsidian",
        "cybersecurity"
      ],
      "slug": "day-01",
      "sourcePath": "Blog/_posts/2026-01-19-day-01.md",
      "contentPath": "/generated/posts/blog/1.json"
    }
  ],
  "labs": [
    {
      "day": 10,
      "title": "Isolating Parallel Agents with Git Worktrees",
      "date": "2026-07-22",
      "url": "https://juribuora.github.io/labs/2026/07/22/lab-10-day-172.html",
      "category": "lab",
      "tags": [
        "cybersecurity",
        "git",
        "worktrees",
        "isolation",
        "multiagent",
        "commandline",
        "bash",
        "changecontrol",
        "labs",
        "learningprocess"
      ],
      "slug": "lab-10-day-172",
      "sourcePath": "Labs/_posts/2026-07-22-lab-10-day-172.md",
      "contentPath": "/generated/posts/lab/10.json"
    },
    {
      "day": 9,
      "title": "Testing an Integrity-Protected Artifact Delivery Path",
      "date": "2026-07-18",
      "url": "https://juribuora.github.io/labs/2026/07/18/lab-09-day-168.html",
      "category": "lab",
      "tags": [
        "cybersecurity",
        "integrity",
        "authorization",
        "hashing",
        "securedelivery",
        "testing",
        "labs"
      ],
      "slug": "lab-09-day-168",
      "sourcePath": "Labs/_posts/2026-07-18-lab-09-day-168.md",
      "contentPath": "/generated/posts/lab/9.json"
    },
    {
      "day": 8,
      "title": "Auditing a Bounded, Source-Attributed Agent Context",
      "date": "2026-07-15",
      "url": "https://juribuora.github.io/labs/2026/07/15/lab-08-day-165.html",
      "category": "lab",
      "tags": [
        "cybersecurity",
        "provenance",
        "dataintegrity",
        "aisecurity",
        "python",
        "testing",
        "labs"
      ],
      "slug": "lab-08-day-165",
      "sourcePath": "Labs/_posts/2026-07-15-lab-08-day-165.md",
      "contentPath": "/generated/posts/lab/8.json"
    },
    {
      "day": 7,
      "title": "Investigating a False-Positive Alert in a Verification Script",
      "date": "2026-07-14",
      "url": "https://juribuora.github.io/labs/2026/07/14/lab-07-day-164.html",
      "category": "lab",
      "tags": [
        "cybersecurity",
        "detectionengineering",
        "falsepositives",
        "bash",
        "git",
        "commandline",
        "triage",
        "labs",
        "learningprocess"
      ],
      "slug": "lab-07-day-164",
      "sourcePath": "Labs/_posts/2026-07-14-lab-07-day-164.md",
      "contentPath": "/generated/posts/lab/7.json"
    },
    {
      "day": 6,
      "title": "Linux User and Group Management for Access Control",
      "date": "2026-07-05",
      "url": "https://juribuora.github.io/labs/2026/07/05/lab-06-day-155.html",
      "category": "lab",
      "tags": [
        "cybersecurity",
        "linux",
        "linuxfundamentals",
        "commandline",
        "bash",
        "accesscontrol",
        "authentication",
        "authorization",
        "labs",
        "learningprocess"
      ],
      "slug": "lab-06-day-155",
      "sourcePath": "Labs/_posts/2026-07-05-lab-06-day-155.md",
      "contentPath": "/generated/posts/lab/6.json"
    },
    {
      "day": 5,
      "title": "SSH Brute-Force Investigation and Automated Defense",
      "date": "2026-03-10",
      "url": "https://juribuora.github.io/labs/2026/03/10/lab-05-day-38.html",
      "category": "lab",
      "tags": [
        "linux",
        "commandline",
        "logs",
        "ssh",
        "networking",
        "cybersecurity",
        "labs"
      ],
      "slug": "lab-05-day-38",
      "sourcePath": "Labs/_posts/2026-03-10-lab-05-day-38.md",
      "contentPath": "/generated/posts/lab/5.json"
    },
    {
      "day": 4,
      "title": "Endpoint Process Chain Triage with Pipe-Delimited Logs and awk",
      "date": "2026-02-26",
      "url": "https://juribuora.github.io/labs/2026/02/26/lab-04-day-29.html",
      "category": "lab",
      "tags": [
        "cybersecurity",
        "linuxfundamentals",
        "commandline",
        "bash",
        "processes",
        "logs",
        "labs",
        "learningprocess"
      ],
      "slug": "lab-04-day-29",
      "sourcePath": "Labs/_posts/2026-02-26-lab-04-day-29.md",
      "contentPath": "/generated/posts/lab/4.json"
    },
    {
      "day": 3,
      "title": "HTTP in Practice (Pentester POV)",
      "date": "2026-02-08",
      "url": "https://juribuora.github.io/labs/2026/02/08/lab-03-day-17.html",
      "category": "lab",
      "tags": [
        "foundations",
        "cybersecurity",
        "webfundamentals",
        "http",
        "labs",
        "learningprocess"
      ],
      "slug": "lab-03-day-17",
      "sourcePath": "Labs/_posts/2026-02-08-lab-03-day-17.md",
      "contentPath": "/generated/posts/lab/3.json"
    },
    {
      "day": 2,
      "title": "Real SUID Behavior: Scripts vs Binaries",
      "date": "2026-02-07",
      "url": "https://juribuora.github.io/labs/2026/02/07/lab-02-day-16.html",
      "category": "lab",
      "tags": [
        "linuxfundamentals",
        "linux",
        "commandline",
        "permissions",
        "processes",
        "cybersecurity",
        "labs"
      ],
      "slug": "lab-02-day-16",
      "sourcePath": "Labs/_posts/2026-02-07-lab-02-day-16.md",
      "contentPath": "/generated/posts/lab/2.json"
    },
    {
      "day": 1,
      "title": "Linux Permissions & Ownership Hands-On Practice",
      "date": "2026-02-05",
      "url": "https://juribuora.github.io/labs/2026/02/05/lab-01_day-14.html",
      "category": "lab",
      "tags": [
        "linuxfundamentals",
        "linux",
        "commandline",
        "permissions",
        "filesystem",
        "cybersecurity",
        "labs",
        "learningprocess"
      ],
      "slug": "lab-01_day-14",
      "sourcePath": "Labs/_posts/2026-02-05-lab-01_day-14.md",
      "contentPath": "/generated/posts/lab/1.json"
    }
  ],
  "allTags": [
    "accesscontrol",
    "aios",
    "aisecurity",
    "approvals",
    "appsec",
    "assetinventory",
    "auditability",
    "auditing",
    "authentication",
    "authorization",
    "automation",
    "automationsecurity",
    "autonomousagents",
    "autonomy",
    "availability",
    "bash",
    "benchmarking",
    "blogging",
    "business",
    "changecontrol",
    "changemanagement",
    "cicd",
    "codereview",
    "commandline",
    "consistency",
    "costtracking",
    "cron",
    "css",
    "cybersecurity",
    "cybersecurityfoundations",
    "dailylog",
    "datagovernance",
    "dataintegrity",
    "debugging",
    "decommissioning",
    "defense",
    "detectionengineering",
    "dns",
    "documentation",
    "ds4",
    "emailsecurity",
    "failclosed",
    "failsafe",
    "falsepositives",
    "featureflags",
    "filepermissions",
    "filesystem",
    "foundations",
    "git",
    "github",
    "githubpages",
    "glossary",
    "googlecert",
    "googlecybersecuritycertificate",
    "governance",
    "grep",
    "hardening",
    "hashing",
    "hermes",
    "homebrew",
    "http",
    "humanintheloop",
    "integrity",
    "ios",
    "isolation",
    "jekyll",
    "kalilinux",
    "knowledgemanagement",
    "labs",
    "learninginpublic",
    "learningprocess",
    "leastprivilege",
    "lifecycle",
    "linux",
    "linuxfundamentals",
    "linuxux",
    "lmstudio",
    "localagents",
    "localai",
    "localfirst",
    "localization",
    "localllm",
    "logging",
    "logs",
    "macbook",
    "macos",
    "mcp",
    "mitre",
    "mobilesecurity",
    "multiagent",
    "networking",
    "obsidian",
    "ollama",
    "operationalsecurity",
    "orchestration",
    "packagemanagement",
    "packets",
    "parallels",
    "permissionmodel",
    "permissions",
    "portfolio",
    "privacy",
    "processes",
    "productsecurity",
    "provenance",
    "python",
    "qualityassurance",
    "rbenv",
    "recovery",
    "reliability",
    "remediation",
    "remoteaccess",
    "remoteagenthub",
    "reporting",
    "resilience",
    "resourcemanagement",
    "riskmanagement",
    "riskscoring",
    "rss",
    "ruby",
    "securedelivery",
    "ssh",
    "staticsite",
    "staticsites",
    "supervisor",
    "swiftui",
    "tailscale",
    "tcpip",
    "technicalwriting",
    "testing",
    "tooling",
    "triage",
    "troubleshooting",
    "tryhackme",
    "ubuntu",
    "ux",
    "validation",
    "verification",
    "virtualmachine",
    "visualization",
    "vscode",
    "webcheckup",
    "webfundamentals",
    "websecurity",
    "websitemaintenance",
    "webtesting",
    "windows",
    "windows11",
    "workflow",
    "worktrees",
    "zeroday"
  ],
  "source": "snapshot",
  "upstream": {
    "repo": "JuriBuora/JuriBuora.github.io",
    "branch": "my-blog",
    "site": "https://juribuora.github.io"
  }
};
